### ISSUE TITLE
请求这个项目的设计文档可以分享出来吗 ： ）

### ISSUE THREAD

**Issue by niukey** [Qihoo360/zeppelin#1]

**Comment by KernelMaker** [comment]
目前项目还在开发中，很多细节还未确定，等完成后会陆续更新到wiki中

**Comment by niukey** [comment]
期待，我现在也是准备使用raft + 一致性hash + rocksdb 搞一个分布式kv存储 ，希望能够与你们多多交流，：）

**Comment by zz198808** [comment]
请问下zeppelin和pika底层存储引擎是不是rocksdb，二者区别是什么？

**Comment by CatKang** [comment]
项目文档，会逐步放到wiki中，目前已经有一些了

**Comment by CatKang** [comment]
底层都是rocksdb，目前没有区别，zeppelin有打算近期做一些调整
