### ISSUE TITLE
zp_node中配置项meta_addr问题

### ISSUE THREAD

**Issue by zhaozhihua2008** [Qihoo360/zeppelin#24]
配置样例：
## Server related
meta_addr : xx.xx.xx.xx/9221,xx.xx.xx.xx/10331

代码：zp_data_server.cc 265   auto pos = addr.find(":");

问题：
1.和meta保持一致的话，应该是按照/分隔吧？
2.这个东西你们大规模应用了吗？

**Comment by gaodq** [comment]
因为之前的版本是用'/'分割，后来改成了':'，但是配置文件的example忘了改，感谢反馈。
公司内部已经有好几个线上业务在用了。
