### ISSUE TITLE
create table error

### ISSUE THREAD

**Issue by zhaozhihua2008** [Qihoo360/zeppelin#25]
创建3个meta在tpd1机器上端口9221,9222,9223
3个node在tpd2机器上，端口13221,13222,13223

执行zk-manager，查看meta，node都正确，但是创建table异常
命令如下：
Zeppelin(tpd1:9221)>> listnode
tpd2:13221 up
tpd2:13222 up
tpd2:13223 up
Zeppelin(tpd1:9221)>> listmeta
Leader:
 --- tpd1:9221, status: Up
Followers:
 --- tpd1:9222, status: Up
 --- tpd1:9223, status: Up
Epoch: -1
Consistency status: 

      Node           |    Role    | Term |      Leader      |      VoteFor      | LastLogTerm | LastLogIdx | CommitIndex | LastApplied |
           tpd1:9322    follower     31          tpd1:9321            tpd1:9321          31        13140         13139        13139
           tpd1:9323    follower     31          tpd1:9321            tpd1:9321          31        13140         13139        13139
           tpd1:9321      leader     31          tpd1:9321            tpd1:9321          31        13140         13140        13140

OK
Zeppelin(tpd1:9221)>> createtable test1 hostlist.txt 2
Checkup distribution result
Node Num: 3
Partition Num: 6
3 replicas in 1 node: 0
2 replicas in 1 node: 0
3 replicas in 1 host: 6
2 replicas in 1 host: 0
3 replicas in 1 cabinet: 6
2 replicas in 1 cabinet: 0
-------------------------
6 partitions node num: 3
+++++++++++++++++++++++++++++++++++++
Continue? (Y/N/dump)
dump
Table name: test1
Partition id: 0 master: 10.31.2.242  :13222 slave0: 10.31.2.242  :13221 slave1: 10.31.2.242  :13223 
Partition id: 1 master: 10.31.2.242  :13223 slave0: 10.31.2.242  :13221 slave1: 10.31.2.242  :13222 
Partition id: 2 master: 10.31.2.242  :13221 slave0: 10.31.2.242  :13222 slave1: 10.31.2.242  :13223 
Partition id: 3 master: 10.31.2.242  :13222 slave0: 10.31.2.242  :13221 slave1: 10.31.2.242  :13223 
Partition id: 4 master: 10.31.2.242  :13223 slave0: 10.31.2.242  :13221 slave1: 10.31.2.242  :13222 
Partition id: 5 master: 10.31.2.242  :13221 slave0: 10.31.2.242  :13222 slave1: 10.31.2.242  :13223 
Continue? (Y/N/dump)
Y
Corruption: Node 10.31.2.242  :13221 is down

**Comment by zhaozhihua2008** [comment]
hostlist.txt 文件如下：
Cab_1
  10.31.2.242  
    13221
    13222
    13223

**Comment by gaodq** [comment]
每次都能复现吗，我确认了下，这不可能啊

**Comment by CatKang** [comment]
这三个节点都起来了吗

**Comment by zhaozhihua2008** [comment]
hostlist.txt 文件修改为如下好了
Cab_1
  tpd2
     13221
     13222
     13223

多谢！
问个问题：
1.现在是有get set操作？没有其他类似redis的hset之类的？
2.现在有java客户端吗？

**Comment by gaodq** [comment]
hostlist.txt
```
Cab_1
  tpd2
    13221
    13222
    13223
```
每一级都要有两个空格缩进
1. 现在还只有基础的kv接口，但在客户端基础上可以封装多种接口，现在支持了table store接口，未来可以考虑支持redis等。
2. java客户端正在开发中https://github.com/Qihoo360/zeppelin-client/issues/16

**Comment by zhaozhihua2008** [comment]
ok.多谢！
