### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Qihoo360/zeppelin#26]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [a destructor like for the class “ZPBinlogSendTask”](https://github.com/Qihoo360/zeppelin/blob/a72d3ce59127c2677e53d464fa3d54de06279119/src/node/zp_binlog_sender.cc#L77 "Destructor for ZPBinlogSendTask").

**Comment by CatKang** [comment]
You are right, would you please fix it and commit then？

**Comment by elfring** [comment]
* Are you quicker (than me) to [delete unneeded if statements](https://github.com/Qihoo360/zeppelin/blob/a72d3ce59127c2677e53d464fa3d54de06279119/src/node/zp_binlog_sender.cc#L77 "Update candidate: Destructor for ZPBinlogSendTask")?
* Would you dare to [introduce smart pointers](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers") there?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Qihoo360/zeppelin/commit/614d52467505a9ab3d48d790574a4eee23b9e81e#diff-24877882d305e6ec4dc13cce34e1763aL77 "Deletion of two unnecessary checks").
