### ISSUE TITLE
about eng grammar

### ISSUE THREAD

**Issue by SLRXXX** [Qihoo360/zeppelin#28]
a Distributed Key-Value Platform which {aim} to {providing} excellent performance
-> aims, provide

**Comment by SLRXXX** [comment]
a reliable key-value storage service that can {scales} to many thousands of devices 
-> scale

**Comment by SLRXXX** [comment]
Zeppelin {based} on some other basic libraries
-> is based

**Comment by CatKang** [comment]
Fixed, thanks
