### ISSUE TITLE
zeppelin make upgrade more smooth

### ISSUE THREAD

**Issue by baotiao** [Qihoo360/zeppelin#9]
@CatKang

**Comment by CatKang** [comment]
初步方案：[Zeppelin 迁移扩容设计（二）—— 简单易用](https://github.com/Qihoo360/zeppelin/wiki/Zeppelin-%E8%BF%81%E7%A7%BB%E6%89%A9%E5%AE%B9%E8%AE%BE%E8%AE%A1%EF%BC%88%E4%BA%8C%EF%BC%89%E2%80%94%E2%80%94--%E7%AE%80%E5%8D%95%E6%98%93%E7%94%A8)

**Comment by CatKang** [comment]
Meta相关方案设计：[Zeppelin 迁移扩容设计（二）—— Meta相关](https://github.com/Qihoo360/zeppelin/wiki/Zeppelin-%E8%BF%81%E7%A7%BB%E6%89%A9%E5%AE%B9%E8%AE%BE%E8%AE%A1%EF%BC%88%E4%B8%89%EF%BC%89%E2%80%94%E2%80%94-Meta%E7%9B%B8%E5%85%B3%E8%AE%BE%E8%AE%A1)

**Comment by CatKang** [comment]
Developing in branch [migrate](https://github.com/Qihoo360/zeppelin/tree/migrate)

**Comment by CatKang** [comment]
Merge and PreRelease In [1.0.0](https://github.com/Qihoo360/zeppelin/releases)

**Comment by CatKang** [comment]
Done
